name: Build and Release PyFocus

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Package PyFocus
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow pyinstaller
      
      - name: Extract version from tag
        id: get_version
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Build with PyInstaller
        run: |
          pyinstaller main.py --noconsole
      
      - name: Copy resources
        run: |
          mkdir -p dist/main/_internal/resources
          xcopy /E /I resources dist\main\_internal\resources
        shell: cmd
      
      - name: Rename executable
        run: |
          move dist\main\main.exe dist\main\PyFocus.exe
        shell: cmd
      
      - name: Create ZIP archive
        run: |
          cd dist
          powershell Compress-Archive -Path main/* -DestinationPath "../PyFocus-${{ steps.get_version.outputs.VERSION }}-x64-windows.zip"
        shell: cmd
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: PyFocus ${{ steps.get_version.outputs.VERSION }}
          draft: true
          files: PyFocus-${{ steps.get_version.outputs.VERSION }}-x64-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}